### ISSUE TITLE
Cannot specify link libraries for target "mingw32" which is not built by   this project.

### ISSUE THREAD

**Issue by DopDie** [llanillo/cmake-sdl2#1]
Erroring out on line 14 of Cmakefiles.txt. Seems like it is unable to specify the link libraries. This is a 64 bit PC btw

**Comment by olahjacobsen** [comment]
Hi, I had the same error, I'm providing what worked for me if anyone comes across this repo in the future.

In CMakeLists.txt:
```cmake_minimum_required(VERSION 3.22)
project(PROJECT_NAME)

set(CMAKE_CXX_STANDARD 14)

add_executable(PROJECT_NAME main.cpp)

# --- SDL2 SETUP ---
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules)
set(SDL2_PATH "SDL2/x86_64-w64-mingw32")

find_package(SDL2 REQUIRED)
include_directories(${SDL2_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} ${SDL2_LIBRARY})
```

The last line with `target_link_libraries(${PROJECT_NAME} ${SDL2_LIBRARY})` was the problem, as when I replaced "PROJECT_NAME" with my actual project's name, it kept the dollar sign and brackets. This is not correct and it should be
`target_link_libraries(PROJECT_NAME ${SDL2_LIBRARY})`.

This simple fix worked for me, hope this helps.

**Comment by DopDie** [comment]
Hey, I was able to fix the issue, as a started fresh and got a new project up and running. Good that you found a workaround as well!
