### ISSUE TITLE
SDL2_IMAGE setup issue

### ISSUE THREAD

**Issue by Cesare077** [llanillo/cmake-sdl2#2]
I followed your instruction ,but the image library still not working. After google it up I find that the I need add ${SDL2_IMAGE_LIBRARIES} to target_link_libraries in the cmakefile.txt. For reference only.

**Comment by llanillo** [comment]
Please make a pull request with the fix so I can integrate it or give an example and I'll do it manually. Thank you

**Comment by llanillo** [comment]
Issue resolved with [#3](https://github.com/llanillo/clion-cmake-sdl2-template/pull/3)

**Comment by llanillo** [comment]
Issue resolved with [#3](https://github.com/llanillo/clion-cmake-sdl2-template/pull/3)
